repos:
repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.10
    exclude: |
        (?x)^(ext-libs)$

repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies:  # Optional: Add plugins or specify versions
      - flake8-bugbear
      - flake8-comprehensions
    exclude: |
        (?x)^(ext-libs)$
